// This code was generated by a tool. Any changes made manually will be lost
// the next time this code is regenerated.
// Generated: Fri, 10 Mar 2017 13:31:19 GMT

using System.Reflection;

[assembly: AssemblyVersion("1.0.20610.0")]
[assembly: AssemblyFileVersion("1.0.20610.1331")]