// This code was generated by a tool. Any changes made manually will be lost
// the next time this code is regenerated.
// Generated: Mon, 06 Jun 2016 07:04:33 GMT

using System.Reflection;

[assembly: AssemblyVersion("1.0.19706.0")]
[assembly: AssemblyFileVersion("1.0.19706.704")]