// This code was generated by a tool. Any changes made manually will be lost
// the next time this code is regenerated.
// Generated: Tue, 28 Jun 2016 16:51:00 GMT

using System.Reflection;

[assembly: AssemblyVersion("1.0.19728.0")]
[assembly: AssemblyFileVersion("1.0.19728.1651")]